[package]
name    = "dioxide"
version = "0.0.1"

readme.workspace = true
description.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
bootloader_api = "0.11.x"
thiserror = { version = "2.0.x", default-features = false }
embedded-graphics = "0.8.x"

[dependencies.dioxide_derive]
path    = "../dioxide_derive"
version = "0.0.1"

[features]
default = ["x86"]
rpi5 = []
x86 = []

[[bin]]
name = "dioxide"
test = false
bench = false