[package]
name    = "dioxide"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader_api = "0.11.x"
thiserror = { version = "2.0.x", default-features = false }

[dependencies.dioxide_derive]
path    = "../dioxide_derive"
version = "*"

[features]
default = ["x86"]
rpi5 = []
x86 = []

[[bin]]
name = "dioxide"
test = false
bench = false