[workspace]
default-members = ["crates/vm"]
members = [
  "crates/*",
]
resolver = "3"

[workspace.package]
readme      = "README.md"
description = "A barebones OS built in Rust"
edition     = "2024"
authors     = ["Gabriel Lugo <dev.gabriel.lugo@gmail.com>"]
license     = "MIT"
keywords    = ["dioxide", "os", "o2"]
categories  = ["os", "embedded"]
repository  = "https://github.com/dioxide-os/dioxide"

[workspace.dependencies]
# bootloader_api = { version = "0.x.x", path = "../../vendor/bootloader/api" }
bootloader = { version = "0.11.x" }
bootloader_api = { version = "0.11.x" }
bootloader-x86_64-common = { version = "0.11.x" }
thiserror = { version = "2.0.x", default-features = false }
log = { version = "0.4.x", default-features = false }
